import sys
from importlib import import_module
from importlib import util as importlib_util

from .auggie import Auggie
from .config import AttackConfig, build_gaggle, load_attack_config
from .util import SAMPLE_TEXT
from .zoo import (
    Adjax,
    Apostrofae,
    Ekkokin,
    Gaggle,
    Glitchling,
    Hokey,
    Jargoyle,
    Mim1c,
    Pedant,
    Redactyl,
    Reduple,
    Rushmore,
    RushmoreMode,
    Scannequin,
    Spectroll,
    Typogre,
    Zeedub,
    adjax,
    apostrofae,
    ekkokin,
    hokey,
    jargoyle,
    mim1c,
    pedant,
    plan_glitchling_specs,
    plan_glitchlings,
    redactyl,
    reduple,
    rushmore,
    scannequin,
    spectroll,
    summon,
    typogre,
    zeedub,
)

__all__ = [
    "Typogre",
    "typogre",
    "Mim1c",
    "mim1c",
    "Jargoyle",
    "jargoyle",
    "Adjax",
    "adjax",
    "Apostrofae",
    "apostrofae",
    "Ekkokin",
    "ekkokin",
    "Hokey",
    "hokey",
    "Pedant",
    "pedant",
    "Redactyl",
    "redactyl",
    "Reduple",
    "reduple",
    "Rushmore",
    "rushmore",
    "RushmoreMode",
    "Spectroll",
    "spectroll",
    "Scannequin",
    "scannequin",
    "Zeedub",
    "zeedub",
    "summon",
    "Glitchling",
    "Gaggle",
    "plan_glitchlings",
    "plan_glitchling_specs",
    "SAMPLE_TEXT",
    "AttackConfig",
    "build_gaggle",
    "load_attack_config",
    "Auggie",
]
